### ISSUE TITLE
Refactoring the existing ggvega - TypeScript

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/ggvega#33]
I think we could use this issue to mirror a PR.

The purpose of the PR will be to refactor the existing ggvega - Typescript code in the context of scatterplot examples.

One part of the refactoring will be to keep track of validation messages (from #6)

----

In ggvega, the building of the encoding is the most-complicated part, because so many elements from ggspec will affect the encoding.

In ggpsec, we have (using "YAMLish" notation):

```yaml
data: 
  <data_name>: 
    metadata: <gsMetadata>
    observations: []
layers:
  - data: <data_name>
    geom: 
      class: <geom_name>
    geom_params: {} # I think this will be coming with Boxplot
    mapping:
      <aes_name>:
        field: <variable_name>
    aes_params:
      <aes_name>: <xxx>
    stat:
      class: <stat_name>
      default_aes: 
        (content depends on <stat_name>)
    stat_params:
      (content depends on <stat_name>)
scales:
  - class: <scale_name>
    aesthetics: 
      - <aes_name>
      - <aes_name>
    (the rest of the content depends on <scale_name>) 
    transform:
      type: <transform_type>
      base: <xxx> 
labels:
  title: <xxx>
  <aes_name>: <xxx>
  <aes_name>: <xxx>
```

We should note that we are working out how to format the information that comes from a ggplot2 `stat`.

In Vega-Lite, within a single layer, a set of encodings will depend on ggpsec:

- layer (corresponding layer)
- data (metadata for the data associated with the corresponding layer)

- scales
- labels
- (coordinates, not yet defined)

One thing I want to keep in mind - and this follows from the ggplot2 philosophy - that all layers share scales and labels - so that we may want to specify a scale (or label) only for the first appearance of an aesthetic in the layers list (or the first appearance of an encoding in the layers list).

I wonder if we could build up a set of encodings with a set of functions - instead of one "big" function.

My next post in this thread will be to propose a first idea of how we could imagine such a set of functions.
